server:
  port: 8088
jwt:
  secret:
    key: secretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecret
spring:
  application:
    name: spring-cloud-gateway
  cloud:
    gateway:
      routes:
        - id: search-service
          uri: lb://search-service
          predicates:
            - Path=/search-service/**
          filters:
            - CustomFilter
            - RewritePath=/search-service(?<segment>/?.*), $\{segment}
        - id: favorite-service
          uri: lb://favorite-service
          predicates:
            - Path=/favorite-service/**
          filters:
            - CustomFilter
            - RewritePath=/favorite-service(?<segment>/?.*), $\{segment}
        - id: user-service
          uri: lb://user-service
          predicates:
           - Path=/user-service/**
          filters:
            - RewritePath=/user-service(?<segment>/?.*), $\{segment}
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
#  instance:
#    hostname: localhost