server:
  port: 8081
jwt:
  secret:
    key: secretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecret
spring:
  application:
    name: user-service
  dataSource:
    url: jdbc:mysql://localhost:3306/registerdetails
    username: root
    password: root
    jpa:
      hibernate:
        ddl-auto: update
      show_sql: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
